ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

We develop an application of questions, like 'Saber y Ganar', in which the main objetive is to comunicate with a chatbot to obtain some hints for answer correctly each question.

We start from a ready-make application, which condition us when making some of the technical decisions.

.Technologies used:
* JavaScript: JavaScript is a very flexible programming language widely used in software development. Besides, we decided to continue with this language due to the base application.
* Node.js: Node.js is used to create server-side applications with JavaScript, so we decided to use it to make the back-end of our web app.
* MongoDB: MongoDB is an open-source NoSQL database that uses a document-based data model for information storage and retrieval. Again its use is mainly due to the legacy project.
* React JS: It's a framework widely used to create user interface components. Chosen for the large volume of documentation and the fact that it is the framework used during the previous app.

=== Decissions made to achieve quality goals
* *Usability*: Although usability is already guaranteed by the developers of the base application, we will try to make interaction with the chatbot simple so that it remains that way.
* *Maintainability*: The entire team is committed to making clean and well-structured code, along with adequate documentation to enable good maintainability of the project.
* *Accessibility*: In the event of making any changes that affect the accessibility of the application, we will ensure that it complies with the appropriate accessibility standards.

=== Relevant organizational decisions
* Communication between team members is mostly made through Github, using issues to create and assign tasks, Whatsapp, to ask the rest of the team for help if needed for quick advice, and meetings.
* For the tasks to be performed, we have decided to implement an author-reviewer mechanic to avoid a single person being in charge of a part of the application and minimize large avoidable errors.

