ifndef::imagesdir[:imagesdir: ../images]

= Architectural decisions

== 9.1 Use of Large Language Models (LLMs) in the System
We will use LLM in our question-and-answer application to generate hints during
the user's turn.

*_Decision:_* +
It was decided to integrate Large Language Models (LLMs) through external APIs to generate real-time responses and hints. +
The selected models are Gemini-1.5-Flash (Google) and Qwen2.5-Coder-7B-Instruct (Empathy AI)
because they are the ones integrated into the base project software.

*Consequences* +
Consequently, we need a structured knowledge source, in our case Wikidata,
from which we will extract and process the information to provide it to the user.

== 9.2 Using Wikidata as the main knowledge base
We require a structured and up-to-date knowledge base, so we decided to utilize Wikidata
as the primary information source.

*Justification*

 - Wikidata is an open, structured database offering information in RDF and SPARQL formats.
 - It enables flexible integrations with our backend systems.

*Consequences*

 - Optimal performance requires expertise in SPARQL query optimization.
 - Data updates are dependent on the Wikidata community.

== 9.3 Choosing React for the Frontend
We require an efficient framework for frontend development so we decided to utilize
React for the user interface.

*Justification*

 - React's declarative nature facilitates the construction of interactive user interfaces.
 - The integration of React with Wikidata is straightforward and user-friendly, simplifying data management and display.
 - It aligns with our existing JavaScript stack used in the backend.

As a consequence, most part of the team will require React training because it is a new technology for many of us.

== 9.4  Using Node.js for Backend Development
We require an efficient and scalable technology for the backend so we will utilize Node.js to solve this problem.

*Justification* +
Node.js is highly efficient for asynchronous and high-traffic applications.
Furthermore, it is a great opportunity for many of us to learn how to use this important technology in the software development world.

== 9.5 Selecting MongoDB for the Database
Due to the requirement for flexible storage of structured and unstructured data,
we have chosen a NoSQL database over SQL.

*Justification*

 - It facilitates the storage of semi-structured data in JSON format.
 - It works very well with Node.js and is highly scalable.

*Consequences* +
Query optimization may be required for handling large data volumes. Although we
have had some exposure to NoSQL databases, further training and development in this area will be necessary to optimize their usage.
ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****
endif::arc42help[]
