ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions

[cols="3,5,3", options="header"]
|===
| Decision | Description | Status

| *JavaScript*
|*Decision:* We will use the JavaScript language to build both the front-end and the back-end of the application.


*Justification:*
We have chosen this technology because it comes from the initial project, and the whole team felt it was the right decision to continue using it.

*Consequences:*
Information about how the language works should be researched.

| *Approved*

| *React*
|*Decision:* We have decided to use ReactJS for the front-end of our project.

*Justification:*
The decision was made because the base project provided to us already used ReactJS, and we considered this a great advantage to get started, as well as an opportunity to familiarize ourselves with a framework that is unfamiliar to many of us.

*Consequences:*
As a consequence, at the beginning, we will have to familiarize ourselves with this new technology for most of us, but we will be able to use the base project as an example.

| *Approved*

|*NodeJs*
|*Decision:* We will use the Node.js framework to develop the application's backend.

*Justification:* This technology was chosen because it is the default in the initial project and the ones we will use
as a reference. The entire team agreed that it was appropriate to continue using it.

*Consequences:* The team members will need to gain more knowledge about how this library works.
|*Approved*

| *MongoDB*
|*Decision:* We have decided to use MongoDB for the development of our project's backend.


*Justification:* The decision was made because the base project and other projects from the previous year used MongoDB. We see this as a great advantage to start with, as well as an opportunity to deepen our knowledge of a database management system that is less common for us compared to MySQL.


*Consequences:* As a result, the learning curve will be steeper at first, but we will be able to take advantage of its benefits as we progress.
| *Approved*
|===

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****
endif::arc42help[]
