name: Build
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs: 
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV
      - name: Install Dependencies
        run: |
          npm --prefix users/authservice ci
          npm --prefix users/userservice ci
          npm --prefix users/statsservice ci
          npm --prefix llmservice ci
          npm --prefix gatewayservice ci
          npm --prefix webapp ci
          npm --prefix wikiquestionservice ci
          npm --prefix apiservice ci
      - name: Run Unit Tests
        run: |
          npm --prefix users/authservice test -- --coverage
          npm --prefix users/userservice test -- --coverage
          npm --prefix users/statsservice test -- --coverage
          npm --prefix llmservice test -- --coverage
          npm --prefix gatewayservice test -- --coverage
          npm --prefix webapp test -- --coverage
          npm --prefix wikiquestionservice test -- --coverage
          npm --prefix apiservice test -- --coverage
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  e2e-tests:
    needs: [ unit-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install global wait-on
        run: npm install -g wait-on

      - name: Install Dependencies
        run: |
          npm --prefix webapp install
          npm --prefix users/authservice install
          npm --prefix users/userservice install
          npm --prefix users/statsservice install
          npm --prefix wikiquestionservice install
          npm --prefix apiservice install
          npm --prefix llmservice install
          npm --prefix gatewayservice install

      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Build Frontend
        run: npm --prefix webapp run build

      - name: Start Services
        run: |
          # Lanza todos los servicios y el frontend (ajusta si usas otro puerto)
          npm --prefix users/authservice start &
          npm --prefix users/userservice start &
          npm --prefix users/statsservice start &
          npm --prefix wikiquestionservice start &
          npm --prefix apiservice start &
          npm --prefix llmservice start &
          npm --prefix gatewayservice start &
          npm --prefix webapp start &

      - name: Wait for Frontend
        run: wait-on http://localhost:3000

      - name: Run E2E Tests
        run: npm --prefix webapp run test:e2e

